name: Get OpenAI recommendation
on:
  pull_request:
    branches: [ "main" ]

jobs:
  get-recommendation:
    runs-on: ubuntu-latest
    name: Get a recommendation from OpenAI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get AI comment
        uses: adanalvarez/openai-security-review@v0
        with:
          openai-token: ${{ secrets.OPENAI_TOKEN }}
          tokens: 2500
          max-files: 5
